"""OpenAI Chat Completions、Completions 和 Embeddings 客户端。"""

from __future__ import annotations

from ._exceptions import (
    APIConnectionError,
    APIError,
    APIStatusError,
    APITimeoutError,
    AuthenticationError,
    BadRequestError,
    ConflictError,
    InternalServerError,
    NotFoundError,
    OpenAIError,
    PermissionDeniedError,
    RateLimitError,
    UnprocessableEntityError,
)
from ._streaming import AsyncStream, Stream
from ._types import NOT_GIVEN, NotGiven
from .async_client import AsyncOpenAI
from .client import OpenAI
from .messages import (
    AIMessage,
    AssistantMessageContent,
    BaseMessage,
    ChatMessage,
    CustomTool,
    CustomToolCall,
    DeveloperMessage,
    FileContentPart,
    FileInput,
    FunctionCall,
    FunctionMessage,
    HumanMessage,
    ImageContentPart,
    ImageURL,
    InputAudio,
    InputAudioContentPart,
    MessageContent,
    MessageContentPart,
    MessageLike,
    MessageToolCall,
    PromptCacheBreakpoint,
    RefusalContentPart,
    SystemMessage,
    TextContentPart,
    TextMessageContent,
    ToolCall,
    ToolMessage,
    UserMessageContent,
    to_openai_messages,
)
from .resources import (
    AsyncChat,
    AsyncChatCompletions,
    AsyncCompletions,
    AsyncEmbeddings,
    Chat,
    ChatCompletions,
    Completions,
    Embeddings,
)
from .types import (
    ChatCompletion,
    ChatCompletionChunk,
    ChatCompletionChunkChoice,
    ChatCompletionChunkDelta,
    ChatCompletionMessage,
    Choice,
    Completion,
    CompletionChoice,
    CompletionChunk,
    CompletionChunkChoice,
    CompletionUsage,
    CreateEmbeddingResponse,
    Embedding,
    EmbeddingUsage,
)

__version__ = "0.1.3"

__all__ = [
    "NOT_GIVEN",
    "AIMessage",
    "APIConnectionError",
    "APIError",
    "APIStatusError",
    "APITimeoutError",
    "AssistantMessageContent",
    "AsyncChat",
    "AsyncChatCompletions",
    "AsyncCompletions",
    "AsyncEmbeddings",
    "AsyncOpenAI",
    "AsyncStream",
    "AuthenticationError",
    "BadRequestError",
    "BaseMessage",
    "Chat",
    "ChatCompletion",
    "ChatCompletionChunk",
    "ChatCompletionChunkChoice",
    "ChatCompletionChunkDelta",
    "ChatCompletionMessage",
    "ChatCompletions",
    "ChatMessage",
    "Choice",
    "Completion",
    "CompletionChoice",
    "CompletionChunk",
    "CompletionChunkChoice",
    "CompletionUsage",
    "Completions",
    "ConflictError",
    "CreateEmbeddingResponse",
    "CustomTool",
    "CustomToolCall",
    "DeveloperMessage",
    "Embedding",
    "EmbeddingUsage",
    "Embeddings",
    "FileContentPart",
    "FileInput",
    "FunctionCall",
    "FunctionMessage",
    "HumanMessage",
    "ImageContentPart",
    "ImageURL",
    "InputAudio",
    "InputAudioContentPart",
    "InternalServerError",
    "MessageContent",
    "MessageContentPart",
    "MessageLike",
    "MessageToolCall",
    "NotFoundError",
    "NotGiven",
    "OpenAI",
    "OpenAIError",
    "PermissionDeniedError",
    "PromptCacheBreakpoint",
    "RateLimitError",
    "RefusalContentPart",
    "Stream",
    "SystemMessage",
    "TextContentPart",
    "TextMessageContent",
    "ToolCall",
    "ToolMessage",
    "UnprocessableEntityError",
    "UserMessageContent",
    "__version__",
    "to_openai_messages",
]
